# Generated by Django 2.1.3 on 2019-07-05 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('LIVING_ROOM', 'Living Room'), ('BATHROOM', 'Bathroom'), ('BEDROOM', 'Bedroom'), ('KITCHEN', 'Kitchen'), ('OUTDOOR', 'Outdoor')], max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date inserted')),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(0, 'Bad'), (1, 'Low'), (2, 'Normal'), (3, 'Good'), (4, 'High'), (5, 'Excellent')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
